# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release Python Package
on:
  workflow_dispatch:

jobs:
  build-linux-cp38:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:

      - uses: actions/checkout@v3
      - name: Build binary wheel 3.8
        run: |
          /opt/python/cp38-cp38/bin/python -m pip install -r build_requirements.txt
          /opt/python/cp38-cp38/bin/python setup.py bdist_wheel

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-linux-3.8
          path: dist

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} x64
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: build package
        run: |
          python -m pip install -r build_requirements.txt
          python setup.py bdist_wheel

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-macos-${{ matrix.python-version }}
          path: dist

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} x64
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: build package
        run: |
          python -m pip install -r build_requirements.txt
          python setup.py bdist_wheel

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-windows-${{ matrix.python-version }}
          path: dist

  notify:
    needs: [build-linux-cp38, build-macos, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Stage linux 3.8
        uses: actions/download-artifact@v2
        with:
          name: dist-linux-3.8

      - name: Stage macos 3.8
        uses: actions/download-artifact@v2
        with:
          name: dist-macos-3.8
#
      - name: Stage windows 3.8
        uses: actions/download-artifact@v2
        with:
          name: dist-windows-3.8

      - name: List files
        run: |
          ls