# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release Python Package
on:
  workflow_dispatch:

jobs:
  build-linux-cp38:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3
#      - name: Build binary wheel
#        run: /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
#
#      - name: Apply auditwheel for manylinux wheel
#        run: auditwheel repair -w dist dist/*
#
#      - name: Remove linux wheel
#        run: rm dist/*-linux_x86_64.whl

#      - name: Archive dist artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: dist-${{ matrix.python-version }}
#          path: dist

      - uses: actions/setup-python@v3
      - name: Running setup.py
        run: |
          python -m pip install -r build_requirements.txt
          python setup.py bdist_wheel

#  build-macos:
#    runs-on: macos-latest
#    strategy:
#      matrix:
#        python-version: ["3.7" , "3.8" , "3.9", "3.10", "3.11"]
#    steps:
#
#      - name: Set up Python ${{ matrix.python-version }} x64
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#          architecture: x64
#
#      - name: Install package dependencies
#        run: pip install cython wheel
#
#      - name: Build binary wheel
#        run: python setup.py bdist_wheel
#
#      - name: Archive dist artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: dist-${{ matrix.python-version }}
#          path: dist
#
#      - name: Running setup.py
#        run: |
#          python -m pip install -r build_requirements.txt
#          python setup.py bdist_wheel
#
#  build-windows:
#    runs-on: windows-latest
#    strategy:
#      matrix:
#        python-version: [ "3.7" , "3.8" , "3.9", "3.10", "3.11" ]
#    steps:
#
#      - name: Download Build Tools for Visual Studio 2019
#        run: Invoke-WebRequest -Uri https://aka.ms/vs/16/rel...
#
#      - name: Run vs_buildtools.exe install
#        run: ./vs_buildtools.exe --quiet --wait --norestart ...
#
#      - name: Archive dist artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: dist-${{ matrix.python-version }}
#          path: dist
#
#      - name: Running setup.py
#        run: |
#          python -m pip install -r build_requirements.txt
#          python setup.py bdist_wheel
